### PR TITLE
Automatic special k-point generation and Total DOS

### PR DESCRIPTION
**Pull request by psavery**
The major changes that come with this commit are:
1. In a band structure dialog, the special k-points are automatically
   generated based upon the curent space group of the crystal (current
   space group will be located in the top left corner). The user can
   still edit them however he/she wants, but it will helpfully
   generate a list of all special k-points as determined from Bilbao.
2. Total DOS calculations are added. In order to significantly help
   in visualizing the DOS, smoothing functions were added to it (the
   smoothing functions are almost identical to the ones used in a
   helper program for Yaehmop written by Greg Landrum). In addition,
   if smoothing is performed, the integral is plotted as a blue line
   whose value is indicated in the top y axis.
3. With total DOS calculations come the ability to accurately
   calculate the Fermi level. The user has the option to display
   the Fermi as a dashed line and/or zero the Fermi level on DOS
   calculations. In addition, if a DOS calculation is performed, the
   Fermi level in the band structure dialog is automatically udpated
   to the calculated value so the user can plot the Fermi and/or zero
   the Fermi in a band structure calculation as well. For this reason,
   it is recommended to perform a total DOS calculation before a
   band structure calculation.

### CODE REVIEW

**Comment by psavery** [comment]
I can probably break this up into two pieces if you want: the automatic special k point generation part and the total DOS part.

But this code here is identical to the one that the students used in Dr. Jochen Autschbach's class here. I sent @ghutchis the manual I made for this (and can send it to anyone else as well who may want to see it).

**Comment by ghutchis** [comment]
I think the main thing will be to get some documentation on these features for release (e.g., separating the text out into Markdown: https://github.com/Avogadro/avogadro.cc/tree/master/_docs/tutorials

**Comment by ghutchis** [comment]
Sorry for putting off the review. This looks fine, although I'd love to see the Greek gamma (Γ) replace the GM in the actual plot.

**Comment by ghutchis** [comment]
I'm going to merge for now, and then documentation and other bits can come in later.

**Pull request merged**
