### PR TITLE
Orca changes with reverted spherical functions

### PR DESCRIPTION
**Pull request by AlbertDeFusco**
For now it may be that we can only have Orca or Gaussian working at one time.

### CODE REVIEW

**Comment by cryos** [comment]
Why would it be one or the other? It would be great to better understand the issue here.

**Comment by AlbertDeFusco** [comment]
I am going to have to go through the equations to see what they were trying to do. There are cases where some codes expect different normalizations and we will have to make special cases for this.

**Comment by cryos** [comment]
Ah OK, that makes sense. Thanks for elaborating a little!

**Comment by ghutchis** [comment]
Just talking with @AlbertDeFusco - this is no worse than 1.1 as far as other codes and adds substantial support for Orca.

**Comment by cryos** [comment]
Sounds good, shame there is a conflict between the two codes but hopefully we can add some conditionals to deal with these inconsistencies between different codes.

**Pull request merged**
