### PR TITLE
Initial support for exporting to VRML 

### PR DESCRIPTION
**Pull request by etp12**
Only been tested on Windows so far.

Current features:
- spheres, bonds, and multibonds appear to be working correctly
- meshes and colored meshes

To do: 
- preview stats about the 3D object in the dialog box (shortest bond, etc)

### CODE REVIEW

**Comment by etp12** [comment]
Screenshot of colored orbitals with scale set to 20.00 mm/Å to make sure it is being scaled correctly:

**Comment by etp12** [comment]
Need to double check and make sure these values are correct.

Dialog reports the smallest sphere and thinnest cylinder of the diameter in mm. This is triggered by clicking the "Calculate Sizes" button(for users to check the sizes before writing to a file) and will also update after clicking render.

**Comment by ghutchis** [comment]
The dialog looks great - maybe we should move the filename / select to the bottom row and put the "calculate size" on the right column above "render" and "Select..."?

**Comment by etp12** [comment]
Does this look a little better? I'll wait to commit it until it looks good.

**Comment by ghutchis** [comment]
Ugh, I went to merge this today and I don't see the revised dialog. Could you commit the new UI?

Thanks!

**Comment by etp12** [comment]
Whoops! Just committed it.

**Comment by ghutchis** [comment]
I had to make a few minor changes in #820 - notably the CMakeLists.txt. Otherwise, it looks great.

**Comment by ghutchis** [comment]
I'm going to order benzene http://shpws.me/MeKh

**Comment by ghutchis** [comment]
OK, this is now in v1.2 - thanks for all the hard work! The orbitals are very cool. :-)

**Pull request closed without merging**
