### PR TITLE
Adapt Eigen3 compatibility patch from Anton Gladky <gladk@debian.org>

### PR DESCRIPTION
**Pull request by ghutchis**
Patch was developed for v1.1.x, requiring some modifications.
Currently does not apply to QTAIM - needs further const work.

Change-Id: I98943d4bc67c2325e73285718c4ab7b45559673e

### CODE REVIEW

**Comment by ghutchis** [comment]
Also, while it compiles, it seems to have trouble creating the correct viewport. I can import atoms, but nothing shows up in the GLWidget.

**Comment by psavery** [comment]
I started reading up a little bit on this:

https://eigen.tuxfamily.org/dox/Eigen2ToEigen3.html

and I compiled this. I think I get the errors that you have. Interestingly, if I draw something and then zoom out a little bit, I CAN draw atoms and see them. But zooming isn't working properly either - it seems to move atoms to the right. So there are definitely some issues... I think it'd be nice to have full Eigen3 support, though.

It seems that the center of the camera is not being put in the right place.

**Comment by ghutchis** [comment]
If you want to work together on an Eigen3 branch, I can set one up. Like you, I suspect the problem is the camera - the hyperplane support was removed.

**Comment by psavery** [comment]
Sure! I would like to work on it some time sooner or later. It may be a few weeks before I can get to it much, though.

**Comment by psavery** [comment]
I ran a little test with the hyperplane stuff here: https://github.com/cryos/avogadro/pull/38/files#diff-44c65ae1c3972a287fd0343ea0515d43R1910

I used an older version of Eigen 3 (like 3.15 or something). I used the code you added and the hyperplane function that used to be there. I compared the coeffs and had it print to me whether they were equal or not. In every case I tested with it (with drawing), they were always equal.

Indeed, with just that one hyperplane change being made, I could still draw without any issues. There appeared to be no issues with the camera, either. It looked the same. So I think your "fitHyperplane" replacement is working fine. I guess that the problem may be elsewhere...

**Comment by csantosbh** [comment]
Hello. I noticed some problems with the way Projective entities are being used along with vectors on this patch, so I created my own modifications here: https://github.com/csantosbh/avogadro/commit/43af3c117b0b3220b15c2fe2895b94bbd83d3a60

There's a couple of compilation issues whose solutions were grabbed from this patch (where I added my own TODOs). If you have a chance to test it, let me know if everything works for you.

**Comment by ghutchis** [comment]
@csantosbh  I'll take a look. When you're ready, please submit a pull request and make sure the qtaim subdirectory is also ported.

Thanks!

**Comment by ghutchis** [comment]
I'm going to close this in favor of #852

**Pull request closed without merging**
