### PR TITLE
Port code to Eigen 3.3

### PR DESCRIPTION
**Pull request by csantosbh**
Most of the port consists of adapting the operations between Projective3d (which actually is represented by a 4x4 matrix) and Vector3d by using the homogeneous coordinate of the vector, effectively transforming <x,y,z> into <x,y,z,1>. This is the expected form of vectors to be used with 4x4 transform matrices.

In this pull request, I steered as much as possible from changing any APIs.

### CODE REVIEW

**Comment by ghutchis** [comment]
Thanks, I'll take a look!

**Comment by ghutchis** [comment]
So far, this looks good. I compiled on the Mac. @cryos - can you take a look on Linux?

**Comment by davethecipo** [comment]
If I can be of any help, this PR compiles on my setup (Arch Linux, eigen 3.3.2-1)

**Comment by sagitter** [comment]
I'm compiling on Fedora. Let me check.

**Comment by cryos** [comment]
Compiles fine for me on Linux (Arch with GCC 6.3.1), the code changes all look reasonable to me. I would be happy to see this merged.

**Comment by sagitter** [comment]
@cryos @davethecipo 

Which commit you used?

**Comment by cryos** [comment]
I used the tip of the branch, 7c23e973ef95f10b774c3e2604b917a108d75155

**Comment by sagitter** [comment]
It's failing for me: https://paste.fedoraproject.org/538285/

Eigen-3.2.10

**Comment by cryos** [comment]
Eigen 3.3.2 here, it could be an API change in Eigen. I don't have time to try an older version right now, but can try and take a look later.

**Comment by cryos** [comment]
This branch is clearly targeting 3.3 from the name, so I am not sure if there is much desire to fall back to older versions. I would hope packagers would also update Eigen if updating Avogadro.

**Comment by sagitter** [comment]
Okay, i need to force `eigen-3.3` updating on Fedora stable in this case.

**Comment by davethecipo** [comment]
@sagitter 7c23e973ef95f10b774c3e2604b917a108d75155

**Comment by csantosbh** [comment]
Breaking the compatibility with Eigen 3.2 is not ideal. I'm working on the issue reported by @sagitter .

**Comment by davethecipo** [comment]
Something changed in my system and I can't compile this anymore. I'll try to make a replicable docker image in order to understand where the problem is.

**Comment by sagitter** [comment]
@csantosbh 
Thanks for your fix.

**Comment by csantosbh** [comment]
@davethecipo Did it break after my last commit? Could you share the compilation log?

**Comment by davethecipo** [comment]
I double checked and it's not that. It must be related to my system because I can't even compile 7c23e973 or master. Sorry for the confusion.

**Comment by ghutchis** [comment]
This looks good to me. I'm going to merge.

**Comment by ghutchis** [comment]
@csantosbh - can you confirm that you received the bounty?

**Comment by csantosbh** [comment]
@ghutchis I just found out that I need to submit a bounty claim. Thanks!

**Pull request merged**
