### PR TITLE
Initial commit for Visual Studio 2015 support

### PR DESCRIPTION
**Pull request by cryos**
Removes variable length array usage in libmsym, this replaces #42

### CODE REVIEW

**Comment by cryos** [comment]
So this patch is breaking compilation on Linux for me, just verified that master builds fresh, but this does not. Just taking a look at it now, will try and get a patch appended shortly.

**Comment by cryos** [comment]
This compiles here, not tested extensively. I doubt this minor fix will cause any new issues with Visual Studio, but can test this afternoon @ghutchis

**Comment by cryos** [comment]
This fails on Visual Studio 2010, which is the only compiler Qt provides Qt 4.8 binaries. Looks like it is all msym using new C features as far as I can tell. I see the value in msym, but wonder if it should at least be optional if it is going to force a new compiler version. I had been wanting to upgrade to Visual Studio 2015, but will need to work through some of the dependencies and make sure they all work too.

If we do in fact require new compiler features then the build system/documentation should be updated to reflect that. It seems like some big changes for this feature, I have other work pushing me to upgrade to new Visual Studio too, it looks like Open Babel already implicitly made the jump as it removed C99 MSVC support libraries last year too.

This commit seems to improve things, but I have not verified compilation as I didn't realize msym requires newer C features not present in VS2010. If you can build it locally definitely merge it, I will see if I can get the dependencies built with VS2015.

**Comment by ghutchis** [comment]
I think I'm going to close this one - libmsym isn't getting rid of VLA any time soon. I'm working with him to get a "reduced set" library (e.g., detection only) without VLA.

**Comment by cryos** [comment]
Sounds like a plan, I know Windows is more limited as far as compiler support is concerned but we need our libraries to be something we can compile with a standard Windows compiler really.

**Pull request closed without merging**
